version: "2.1"
services:
  chromium:
    image: ljc359120730/chromium:v3
    container_name: chromium
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - CHROME_CLI=https://www.linuxserver.io/ #optional
    volumes:
      - ./config:/config
      - /data:/data
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
